program
  declList
    decl
      funDecl
        funcTypeName
          typeSpecifier,int
          identifier,main
        funBody
          statementList
    decl
      funDecl
        funcTypeName
          typeSpecifier,char
          identifier,main2
        formalDeclList
          formalDecl
            typeSpecifier,int
            identifier,arg1
        funBody
          statementList
    decl
      funDecl
        funcTypeName
          typeSpecifier,void
          identifier,main3
        formalDeclList
          formalDecl
            typeSpecifier,void
            identifier,arg1
          formalDecl
            typeSpecifier,char
            identifier,arg2
        funBody
          statementList
SYMBOL TABLE:
36: char :main2()
37: void :main3()
242: int :main()
384: int main2:arg1
385: void main3:arg1
386: char main3:arg2[]
